name: helpdesk_mobile
description: A Flutter mobile app for HelpDesk
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.5
  socket_io_client: ^2.0.3+1
  intl: ^0.19.0
  device_info_plus: ^9.1.2
  package_info_plus: ^8.0.0

  # For JSON annotations if needed later
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true